language: generic
sudo: true
dist: xenial

# whitelist of branches to build
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

before_script:

script:
  - make
  - git clone https://github.com/commoncriteria/csfc.github.io.git
  - mkdir -p csfc.github.io/pp/$(basename $TRAVIS_REPO_SLUG)
  - rm -rf csfc.github.io/pp/$(basename $TRAVIS_REPO_SLUG)/*
  - cp -r output/* csfc.github.io/pp/$(basename $TRAVIS_REPO_SLUG)
  - cd csfc.github.io
  - git add --all 
  - git diff-index --quiet HEAD || git commit -m "Deploying changes"
  - git pull --rebase
  - cd -
  
# Deploy HTML pages and updated index.html (needed before we can generate pdf versions)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: csfc.github.io/
  repo: csfc/csfc.github.io
  target_branch: master
  on:
    branch: master
